apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-config
  namespace: kafka
data:
  kafka-jmx-config.yml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
      - pattern: 'kafka.server<type=(.+), name=(.+)><>Value'
        name: kafka_server_$1_$2
        type: GAUGE