apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - kafka-jmx-configmap.yaml
  - kafka-deployment.yaml
  - kafka-service.yaml
  - kafka-servicemonitor.yaml